# Generated by Django 5.0.6 on 2024-07-05 12:58

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_title', models.CharField(max_length=100)),
                ('lab_desc', tinymce.models.HTMLField()),
                ('lab_image', models.FileField(default=None, max_length=250, null=True, upload_to='mayoclinic/')),
                ('lab_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='mayoclinic_title', unique=True)),
            ],
        ),
    ]
